language: node_js
sudo: false
node_js:
  - 14
install:
  - npm install
script:
  - echo "Construido"
addons:
  ssh_known_hosts:
    - 164.41.76.30:13508
before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in .travis/deploy_rsa.enc -out .travis/id_rsa -d
  - eval "$(ssh-agent -s)"
  - cp .travis/id_rsa ~/.ssh/deploy_rsa
  - chmod 600 ~/.ssh/deploy_rsa
  - ssh-add ~/.ssh/deploy_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: bash .travis/deploy.sh
    on:
      branch: teste-deploy-automatico
