version: "3.3"
services:
  dodfminer-dash:
    build:
      context: .
    network_mode: host
    image: dodfminer-dash
    container_name: dodfminer-dash
    ports:
      - "80:80"
    environment:
      - TARGET=LIVE
    restart: unless-stopped