export const actsData = {
    'abono': {title: 'Abono', color: "#a3218e"},
    'aposentadoria': {title: 'Aposentadoria', color: "#592f93"},
    'cessao': {title: 'Cessões', color: "#21409a"},
    'cessoes': {title: 'Cessões', color: "#21409a"},
    'nomeacao_efetiva': {title: 'Nomeação - Efetivos', color: "#0465b2"},
    'efetivos_nome': {title: 'Nomeação - Efetivos', color: "#0465b2"},
    'exoneracao_efetivos': {title: 'Exoneração - Efetivos', color: "#00acac"},
    'efetivos_exo': {title: 'Exoneração - Efetivos', color: "#00acac"},
    'exoneracao': {title: 'Exoneração', color: "#03a45e"},
    'nomeacao_comissionada': {title: 'Nomeação', color: "#72bd46"},
    'nomeacao': {title: 'Nomeação', color: "#72bd46"},
    'retificacao': {title: 'Retificações', color: "#fef102"},
    'retificacoes': {title: 'Retificações', color: "#fef102"},
    'reversao': {title: 'Reversões', color: "#f8a51b"},
    'reversoes': {title: 'Reversões', color: "#f8a51b"},
    'tornado_sem_efeito': {title: 'Aposentadoria Tornada Sem Efeito', color: "#f58225"},
    'sem_efeito_aposentadoria': {title: 'Aposentadoria Tornada Sem Efeito', color: "#f58225"},
    'substituicao': {title: 'Substituição', color: "#ed403c"},
}