export const searchTable = {
    heading: [
        {name: 'SEI', key: 'sei'},
        {name: 'Nome', key: 'nome'},
        {name: 'Matrícula', key: 'matricula'},
        {name: 'Órgão', key: 'orgao'},
        {name: 'DODF Número', key: 'dodf_numero'},
        {name: 'DODF Nome', key: 'dodf_nome'},
        {name: 'Data DODF', key: 'data_dodf'},
        {name: 'Quadro', key: 'quadro'},
        {name: 'Padrão', key: 'padrao'},
        {name: 'Cargo', key: 'cargo'},
        {name: 'Efetivo', key: 'efetivo'},
        {name: 'Classe', key: 'classe'},
    ],
    data: [
        {
            sei: '060.00047003/2017-40',
            nome: 'LUIZ SERGIO MAGALHAES BRAGA',
            matricula: '',
            orgao: '',
            dodf_numero: '001',
            dodf_nome: 'DODF 001 02-01-2018.pdf',
            dodf_Data: '02/01/2018',
            quadro: 'Quadro de Pessoal da Secretaria de Estado de Saude do Distrito Federal',
            padrão: 'Padrao IV\', \'Padrao V',
            cargo: 'Medico Cirurgia Geral\' \'Tecnico em Saude',
            efetivo: '',
            classe: 'Classe Especial',
        },
        {
            sei: '060.00047003/2017-40',
            nome: 'LUIZ SERGIO MAGALHAES BRAGA',
            matricula: '',
            orgao: '',
            dodf_numero: '001',
            dodf_nome: 'DODF 001 02-01-2018.pdf',
            dodf_Data: '02/01/2018',
            quadro: 'Quadro de Pessoal da Secretaria de Estado de Saude do Distrito Federal',
            padrão: 'Padrao IV\', \'Padrao V',
            cargo: 'Medico Cirurgia Geral\' \'Tecnico em Saude',
            efetivo: '',
            classe: 'Classe Especial',
        },
        {
            sei: '060.00047003/2017-40',
            nome: 'LUIZ SERGIO MAGALHAES BRAGA',
            matricula: '',
            orgao: '',
            dodf_numero: '001',
            dodf_nome: 'DODF 001 02-01-2018.pdf',
            dodf_Data: '02/01/2018',
            quadro: 'Quadro de Pessoal da Secretaria de Estado de Saude do Distrito Federal',
            padrão: 'Padrao IV\', \'Padrao V',
            cargo: 'Medico Cirurgia Geral\' \'Tecnico em Saude',
            efetivo: '',
            classe: 'Classe Especial',
        },
    ]
}

